[package]
name = "pam-rust-template"
version = "0.0.1"
edition = "2021"
authors = ["Abran DeCarlo <abrandecarlo@protonmail.com>"]

[dependencies]

rust-embed = "6.4.1"
clap = { version = "4.0.17", features = [ "derive" ] }
eyre = "0.6"
fancy-regex = "0.10.0"
