run: module client

module:
  @cargo build --release --manifest-path=module/Cargo.toml
  sudo cp module/conf/template-pam /etc/pam.d/template-pam
  sudo cp ../../target/release/libpam_template.so \
  /lib/x86_64-linux-gnu/security/pam_template.so
  sudo chmod 755 /lib/x86_64-linux-gnu/security/pam_template.so

client:
  @cargo build --release --manifest-path=client/Cargo.toml
  ../../target/release/pam-client-template
