[package]
name = "pam-module-template"
version = "0.1.0"
authors = ["Abran DeCarlo <abrandecarlo@protonmail.com>"]

[lib]
name = "pam_template"
crate-type = ["cdylib"]

[dependencies]
pam-bindings = "0.1.1"
users = "0.11.0"
